/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shoppar.cv;

public class Detector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Detector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Detector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ShopparJNI.delete_Detector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Detector get() {
    return new Detector(ShopparJNI.Detector_get(), false);
  }

  public Rectangles detect(org.opencv.core.Mat image, int adjust_threshold) {
    return new Rectangles(ShopparJNI.Detector_detect__SWIG_0(swigCPtr, this, image.getNativeObjAddr(), adjust_threshold), true);
  }

  public Rectangles detect(org.opencv.core.Mat image) {
    return new Rectangles(ShopparJNI.Detector_detect__SWIG_1(swigCPtr, this, image.getNativeObjAddr()), true);
  }

}
