/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shoppar.cv;

public class GARecognizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GARecognizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GARecognizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ShopparJNI.delete_GARecognizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class Result {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Result(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Result obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ShopparJNI.delete_GARecognizer_Result(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setGender(Gender value) {
      ShopparJNI.GARecognizer_Result_gender_set(swigCPtr, this, value.swigValue());
    }
  
    public Gender getGender() {
      return Gender.swigToEnum(ShopparJNI.GARecognizer_Result_gender_get(swigCPtr, this));
    }
  
    public void setAge(int value) {
      ShopparJNI.GARecognizer_Result_age_set(swigCPtr, this, value);
    }
  
    public int getAge() {
      return ShopparJNI.GARecognizer_Result_age_get(swigCPtr, this);
    }
  
    public Result(Gender _gender, int _age) {
      this(ShopparJNI.new_GARecognizer_Result__SWIG_0(_gender.swigValue(), _age), true);
    }
  
    public Result(Gender _gender) {
      this(ShopparJNI.new_GARecognizer_Result__SWIG_1(_gender.swigValue()), true);
    }
  
    public Result() {
      this(ShopparJNI.new_GARecognizer_Result__SWIG_2(), true);
    }
  
  }

  public static GARecognizer create() {
    long cPtr = ShopparJNI.GARecognizer_create();
    return (cPtr == 0) ? null : new GARecognizer(cPtr, false);
  }

  public boolean recognize(org.opencv.core.Mat face_image, GARecognizer.Result res) {
    return ShopparJNI.GARecognizer_recognize(swigCPtr, this, face_image.getNativeObjAddr(), GARecognizer.Result.getCPtr(res), res);
  }

}
