/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shoppar.cv;

public final class Gender {
  public final static Gender UNKNOWN = new Gender("UNKNOWN");
  public final static Gender FEMALE = new Gender("FEMALE");
  public final static Gender MALE = new Gender("MALE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Gender swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Gender.class + " with value " + swigValue);
  }

  private Gender(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Gender(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Gender(String swigName, Gender swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Gender[] swigValues = { UNKNOWN, FEMALE, MALE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

