/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shoppar.cv;

public class Rectangles extends java.util.AbstractList<Rect> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Rectangles(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Rectangles obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ShopparJNI.delete_Rectangles(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Rectangles(Rect[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Rect element : initialElements) {
      add(element);
    }
  }

  public Rectangles(Iterable<Rect> initialElements) {
    this();
    for (Rect element : initialElements) {
      add(element);
    }
  }

  public Rect get(int index) {
    return doGet(index);
  }

  public Rect set(int index, Rect e) {
    return doSet(index, e);
  }

  public boolean add(Rect e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Rect e) {
    modCount++;
    doAdd(index, e);
  }

  public Rect remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Rectangles() {
    this(ShopparJNI.new_Rectangles__SWIG_0(), true);
  }

  public Rectangles(Rectangles other) {
    this(ShopparJNI.new_Rectangles__SWIG_1(Rectangles.getCPtr(other), other), true);
  }

  public long capacity() {
    return ShopparJNI.Rectangles_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ShopparJNI.Rectangles_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ShopparJNI.Rectangles_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ShopparJNI.Rectangles_clear(swigCPtr, this);
  }

  public Rectangles(int count, Rect value) {
    this(ShopparJNI.new_Rectangles__SWIG_2(count, Rect.getCPtr(value), value), true);
  }

  private int doSize() {
    return ShopparJNI.Rectangles_doSize(swigCPtr, this);
  }

  private void doAdd(Rect x) {
    ShopparJNI.Rectangles_doAdd__SWIG_0(swigCPtr, this, Rect.getCPtr(x), x);
  }

  private void doAdd(int index, Rect x) {
    ShopparJNI.Rectangles_doAdd__SWIG_1(swigCPtr, this, index, Rect.getCPtr(x), x);
  }

  private Rect doRemove(int index) {
    return new Rect(ShopparJNI.Rectangles_doRemove(swigCPtr, this, index), true);
  }

  private Rect doGet(int index) {
    return new Rect(ShopparJNI.Rectangles_doGet(swigCPtr, this, index), false);
  }

  private Rect doSet(int index, Rect val) {
    return new Rect(ShopparJNI.Rectangles_doSet(swigCPtr, this, index, Rect.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    ShopparJNI.Rectangles_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
