/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shoppar.cv;

public class Shoppar implements ShopparConstants {
  public static boolean init(String license_key, String working_dir) {
    return ShopparJNI.init(license_key, working_dir);
  }

}
