/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shoppar.cv;

public class ShopparJNI {
  public final static native boolean init(String jarg1, String jarg2);
  public final static native void GARecognizer_Result_gender_set(long jarg1, GARecognizer.Result jarg1_, int jarg2);
  public final static native int GARecognizer_Result_gender_get(long jarg1, GARecognizer.Result jarg1_);
  public final static native void GARecognizer_Result_age_set(long jarg1, GARecognizer.Result jarg1_, int jarg2);
  public final static native int GARecognizer_Result_age_get(long jarg1, GARecognizer.Result jarg1_);
  public final static native long new_GARecognizer_Result__SWIG_0(int jarg1, int jarg2);
  public final static native long new_GARecognizer_Result__SWIG_1(int jarg1);
  public final static native long new_GARecognizer_Result__SWIG_2();
  public final static native void delete_GARecognizer_Result(long jarg1);
  public final static native long GARecognizer_create();
  public final static native void delete_GARecognizer(long jarg1);
  public final static native boolean GARecognizer_recognize(long jarg1, GARecognizer jarg1_, long jarg2, long jarg3, GARecognizer.Result jarg3_);
  public final static native void Rect_x_set(long jarg1, Rect jarg1_, int jarg2);
  public final static native int Rect_x_get(long jarg1, Rect jarg1_);
  public final static native void Rect_y_set(long jarg1, Rect jarg1_, int jarg2);
  public final static native int Rect_y_get(long jarg1, Rect jarg1_);
  public final static native void Rect_width_set(long jarg1, Rect jarg1_, int jarg2);
  public final static native int Rect_width_get(long jarg1, Rect jarg1_);
  public final static native void Rect_height_set(long jarg1, Rect jarg1_, int jarg2);
  public final static native int Rect_height_get(long jarg1, Rect jarg1_);
  public final static native long new_Rect(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void delete_Rect(long jarg1);
  public final static native long Detector_get();
  public final static native void delete_Detector(long jarg1);
  public final static native long Detector_detect__SWIG_0(long jarg1, Detector jarg1_, long jarg2, int jarg3);
  public final static native long Detector_detect__SWIG_1(long jarg1, Detector jarg1_, long jarg2);
  public final static native long new_Rectangles__SWIG_0();
  public final static native long new_Rectangles__SWIG_1(long jarg1, Rectangles jarg1_);
  public final static native long Rectangles_capacity(long jarg1, Rectangles jarg1_);
  public final static native void Rectangles_reserve(long jarg1, Rectangles jarg1_, long jarg2);
  public final static native boolean Rectangles_isEmpty(long jarg1, Rectangles jarg1_);
  public final static native void Rectangles_clear(long jarg1, Rectangles jarg1_);
  public final static native long new_Rectangles__SWIG_2(int jarg1, long jarg2, Rect jarg2_);
  public final static native int Rectangles_doSize(long jarg1, Rectangles jarg1_);
  public final static native void Rectangles_doAdd__SWIG_0(long jarg1, Rectangles jarg1_, long jarg2, Rect jarg2_);
  public final static native void Rectangles_doAdd__SWIG_1(long jarg1, Rectangles jarg1_, int jarg2, long jarg3, Rect jarg3_);
  public final static native long Rectangles_doRemove(long jarg1, Rectangles jarg1_, int jarg2);
  public final static native long Rectangles_doGet(long jarg1, Rectangles jarg1_, int jarg2);
  public final static native long Rectangles_doSet(long jarg1, Rectangles jarg1_, int jarg2, long jarg3, Rect jarg3_);
  public final static native void Rectangles_doRemoveRange(long jarg1, Rectangles jarg1_, int jarg2, int jarg3);
  public final static native void delete_Rectangles(long jarg1);
}
